Us/12 base
LarsingDash/BlockyEngine pull request #19
Opened 2024-12-06 19:43 UTC by Kampf-Hoff

fire and forget audio, 1 volume, 0 repeat, but up to 8 channels concurrently.

2024-12-08 13:29 UTC, LarsingDash requested changes
Goede implementatie en werkt goed, ik ben alleen niet geheel tevreden met de structuur. Veel van de SDL_mixer logica zit in de engine-laag (in de component), dat moet juist in de AudioModule. Zorg ervoor dat alles van SDL_mixer naar de AudioModule verplaatst wordt. Daarnaast is het ook het idee dat de .Play() methode wordt aangeroepen op de Audio component, niet de AudioModule

2024-12-08 13:29 UTC, LarsingDash commented on engine/CMakeLists.txt
Werkt niet op Linux, @Dogukan-lab kan hier misschien nog ff naar kijken

2024-12-08 13:29 UTC, LarsingDash commented on engine/components/audio/Audio.cpp
Het werkt goed, ik ben alleen niet geheel blij met de structuur. Implementatie-specifieke dingen als SDL en SDL_mixer doe je hier namelijk allemaal in de Component, hiervoor is juist de module bedoelt. Kijk of dit naar de AudioModule verplaastst kan worden

2024-12-08 13:29 UTC, LarsingDash commented on engine/components/audio/Audio.cpp
> +int Audio::Play(int loops) {
Play en Stop logica moet dus echt in de module zitten, en dan is het idee dat je bij de component .Play() doet, en dat dat in de module wordt afgehandeld. Nu doe je in de sceneManager .Play() op de module...

2024-12-08 13:29 UTC, LarsingDash commented on engine/components/audio/Audio.hpp
> +struct AudioFragment {
Deze struct zou bijvoorbeeld ook in de audioModule moeten

2024-12-08 13:29 UTC, LarsingDash commented on engine/moduleManager/modules/audio/AudioModule.cpp
Dit is dus het enige bestand waar SDL_mixer in gebruikt moet worden. hier moet alle logica komen te staan

2024-12-11 11:44 UTC, Kampf-Hoff commented on engine/CMakeLists.txt
@Dogukan-- "Dat wordt denk ik later fixen, want Linux (aangezien Valgrind suboptimal werkt voor wat we nodig hebben) heeft op het moment geen prio"

2024-12-11 12:28 UTC, LarsingDash approved these changes
Nice goeie aanpassingen

2024-12-11 12:54 UTC, merged